[package]
name = "lc3-zk-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.197", features=["derive"]}

[lib]
name = "lc3"
path = "src/lib.rs"
